apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: golb
spec:
  replicas: 3 # K8s will run 3 backend pods
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: backend
          # --- IMPORTANT ---
          # Replace this with the path to your backend image in OCI Registry
          image: <your-registry-path>/go-backend:latest
          ports:
            - containerPort: 9003
          command: ["/go-backend", "-port", "9003", "K8s-Backend-Pod"]
---
# We create two services pointing to this one deployment
apiVersion: v1
kind: Service
metadata:
  name: api-service # This provides the DNS name "api-service.golb.svc.cluster.local"
  namespace: golb
spec:
  selector:
    app: go-backend # Selects the pods from the deployment
  ports:
    - protocol: TCP
      port: 9001 # The port our Go LB expects
      targetPort: 9003 # The port the container is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: web-service # This provides the DNS name "web-service.golb.svc.cluster.local"
  namespace: golb
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 9003 # The port our Go LB expects
      targetPort: 9003
